import os
import threading
from flask import Flask, render_template, request, jsonify
from flask_socketio import SocketIO, emit
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
import base64
from gtts import gTTS

# Import our custom core components
from core.audio_io import AudioController
from core.brain import GarudaBrain
from core.database import VoiceLedger
from modules.agri_agent import AgricultureAgent
from modules.health_agent import HealthAgent

app = Flask(__name__)
app.config['SECRET_KEY'] = 'garuda_sanket_god_mode_2026'
socketio = SocketIO(app, cors_allowed_origins="*")

# Initialize global controllers
audio = AudioController()
brain = GarudaBrain()
ledger = VoiceLedger()
agri = AgricultureAgent(ledger, brain)
health = HealthAgent(ledger, brain)

# Keep track of current session state
session = {
    "language": "en",
    "city": None,
    "domain": None,
    "user_phone": "9876543210" # Default for demo; in production, capture from gateway
}

@app.route('/')
def index():
    return render_template('dashboard.html')

@app.route('/buyer')
def buyer():
    return render_template('buyer_dashboard.html')

@app.route('/panchayat')
def panchayat():
    return render_template('panchayat_dashboard.html')

@app.route('/send_pdf_report', methods=['POST'])
def send_pdf_report():
    try:
        data = request.json
        pdf_base64 = data.get('pdf_data')
        
        if not pdf_base64:
            return jsonify({'status': 'error', 'msg': 'No PDF data provided'}), 400

        # Decode base64
        pdf_data = base64.b64decode(pdf_base64.split(',')[1])

        # Email details
        sender_email = "u6973364@gmail.com"
        sender_password = "iquraorjiuvhrqsj"
        receiver_email = "u6973364@gmail.com"

        # Construct email
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = receiver_email
        msg['Subject'] = "Panchayat Analytics Report - Garuda Sanket"

        body = "Attached is the latest Panchayat Analytics Dashboard report generated by the Garuda Sanket system."
        msg.attach(MIMEText(body, 'plain'))

        # Attach PDF
        part = MIMEApplication(pdf_data, Name="Panchayat_Analytics_Report.pdf")
        part['Content-Disposition'] = 'attachment; filename="Panchayat_Analytics_Report.pdf"'
        msg.attach(part)

        # Send Email
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()

        return jsonify({'status': 'success', 'msg': 'Email sent successfully'})
    except Exception as e:
        print(f"Error sending email: {e}")
        return jsonify({'status': 'error', 'msg': str(e)}), 500

# --- SOCKET EVENTS: DASHBOARD CONTROLS ---

@socketio.on('trigger_start')
def handle_start():
    print("\n[ACTION] New Call Triggered via Dashboard")
    emit('status_update', {'msg': 'Call Started from Remote'}, broadcast=True)
    audio.play_intro("en") # Start with English prompt

@socketio.on('select_language')
def handle_language(data):
    session['language'] = data['lang']
    print(f"\n[ACTION] Language Selected: {session['language'].upper()}")
    emit('status_update', {'msg': f'Language set to {data["lang"].upper()}'}, broadcast=True)
    # Play confirmation/next menu (City Selection)
    if session['language'] == 'en':
        text = "Please select your city. Press 1 for Bangalore, 2 for Mysore, 3 for Mandya, 4 for Hassan."
    else:
        text = "ದಯವಿಟ್ಟು ನಿಮ್ಮ ನಗರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ. ಬೆಂಗಳೂರಿಗಾಗಿ 1, ಮೈಸೂರಿಗಾಗಿ 2, ಮಂಡ್ಯಕ್ಕಾಗಿ 3, ಹಾಸನಕ್ಕಾಗಿ 4 ಒತ್ತಿ."
        
    path = generate_ai_voice(text, session['language'])
    audio.play_voice(path)

@socketio.on('select_city')
def handle_city(data):
    session['city'] = data['city']
    print(f"\n[ACTION] City Selected: {session['city'].upper()}")
    emit('status_update', {'msg': f'City set to {data["city"].upper()}'}, broadcast=True)
    
    # After city is selected, ask for Domain
    if session['language'] == 'en':
        text = "For agriculture press 1 and for healthcare press 2."
    else:
        text = "ಕೃಷಿಗಾಗಿ 1 ಒತ್ತಿ ಮತ್ತು ಆರೋಗ್ಯ ಸೇವೆಗಾಗಿ 2 ಒತ್ತಿ."
        
    path = generate_ai_voice(text, session['language'])
    audio.play_voice(path)

@socketio.on('select_domain')
def handle_domain(data):
    session['domain'] = data['domain']
    print(f"\n[ACTION] Domain Selected: {session['domain'].upper()}")
    emit('status_update', {'msg': f'Domain Selected: {data["domain"].upper()}'}, broadcast=True)
    # Play specific sub-menu audio or welcome to the sector
    if session['domain'] == 'agriculture':
        if session['language'] == 'en':
            text = "You selected Agriculture. Press 1 for Market Price, 2 for Pest Report, 3 for Sarkari Help."
        else:
            text = "ನೀವು ಕೃಷಿಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿದ್ದೀರಿ. ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಾಗಿ 1, ಕೀಟ ವರದಿಗಾಗಿ 2, ಸರ್ಕಾರಿ ಸಹಾಯಕ್ಕಾಗಿ 3 ಒತ್ತಿ."
    else:
        text = health.get_main_menu(session.get('language', 'en'))
            
    path = generate_ai_voice(text, session.get('language', 'en'))
    audio.play_voice(path)

@socketio.on('health_action')
def handle_health_action(data):
    action = data['action']
    print(f"\n[ACTION] Health Action Triggered: {action.upper()}")
    emit('status_update', {'msg': f'Health Action: {action.upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    if action == 'bp':
        text = health.get_bp_menu(lang)
    elif action == 'symptom':
        intro = health.get_symptom_intro(lang)
        menu = health.get_symptom_menu(lang)
        text = f"{intro} {menu}"
    elif action == 'sugar':
        text = health.get_sugar_menu(lang)
    elif action == 'medicine':
        # Placeholder for Medicine Reminder
        text = health.get_medicine_reminder(lang)
    else:
        text = "Invalid selection."
        
    path = generate_ai_voice(text, lang)
    audio.play_voice(path)

@socketio.on('sugar_action')
def handle_sugar_action(data):
    level = data['level']
    print(f"\n[ACTION] Sugar Action Triggered: {level.upper()}")
    emit('status_update', {'msg': f'Sugar Range: {level.upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    threading.Thread(target=audio.play_buffer).start()
    
    advice = health.get_sugar_advice(level, lang)
    safety = health.get_safety_message(lang)
    text = f"{advice} {safety}"
    
    print(f"\n[AI RESPONSE] {text}")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    
    path = generate_ai_voice(text, lang)
    audio.stop_buffer()
    audio.play_voice(path)

@socketio.on('bp_action')
def handle_bp_action(data):
    level = data['level']
    print(f"\n[ACTION] BP Action Triggered: {level.upper()}")
    emit('status_update', {'msg': f'BP Range: {level.upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    threading.Thread(target=audio.play_buffer).start()
    
    advice = health.get_bp_advice(level, lang)
    safety = health.get_safety_message(lang)
    text = f"{advice} {safety}"
    
    print(f"\n[AI RESPONSE] {text}")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    
    path = generate_ai_voice(text, lang)
    audio.stop_buffer()
    audio.play_voice(path)

@socketio.on('symptom_action')
def handle_symptom_action(data):
    symptom = data['symptom']
    print(f"\n[ACTION] Symptom Triggered: {symptom.upper()}")
    emit('status_update', {'msg': f'Symptom: {symptom.replace("_", " ").upper()}'}, broadcast=True)
    lang = session.get('language', 'en')
    
    threading.Thread(target=audio.play_buffer).start()
    
    advice = health.get_symptom_advice(symptom, lang)
    safety = health.get_safety_message(lang)
    text = f"{advice} {safety}"
    
    print(f"\n[AI RESPONSE] {text}")
    emit('status_update', {'msg': f'AI: {text}'}, broadcast=True)
    
    path = generate_ai_voice(text, lang)
    audio.stop_buffer()
    audio.play_voice(path)


@socketio.on('agri_action')
def handle_agri(data):
    action = data['action']
    print(f"\n[ACTION] Agri Action Triggered: {action.upper()}")
    emit('status_update', {'msg': f'Agri Action: {action.replace("_", " ").upper()}'}, broadcast=True)
    
    # 1. Start thinking sound
    threading.Thread(target=audio.play_buffer).start()
    
    # 2. Process logic based on action
    if action == 'market_price':
        response_text = agri.get_market_intelligence(session['user_phone'], session['language'])
    elif action == 'pest_report':
        response_text = agri.process_pest_report(session['user_phone'], session['language'])
    elif action == 'sarkari_help':
        response_text = agri.get_scheme_eligibility(session['user_phone'], session['language'])
    else:
        if session['language'] == 'en':
            response_text = "I am ready to help with your farming needs."
        else:
            response_text = "ನಿಮ್ಮ ಕೃಷಿ ಅಗತ್ಯಗಳಿಗೆ ಸಹಾಯ ಮಾಡಲು ನಾನು ಸಿದ್ಧನಿದ್ದೇನೆ."

    # 3. TTS Generation & Playback
    path = generate_ai_voice(response_text, session['language'])
    audio.play_voice(path)
    print(f"AI Response: {response_text}")

@socketio.on('market_response')
def handle_market_response(data):
    response = data['response']
    print(f"\n[ACTION] Market Response: {response.upper()}")
    emit('status_update', {'msg': f'Market Response: {response.upper()}'}, broadcast=True)
    
    if response == 'agree':
        text = "Great! We have recorded your interest in selling at this rate. Our agent will contact you soon." if session['language'] == 'en' else "ಉತ್ತಮ! ಈ ದರದಲ್ಲಿ ಮಾರಾಟ ಮಾಡಲು ನಿಮ್ಮ ಆಸಕ್ತಿಯನ್ನು ನಾವು ದಾಖಲಿಸಿದ್ದೇವೆ. ನಮ್ಮ ಏಜೆಂಟ್ ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತಾರೆ."
        
        import random
        price = random.randint(2000, 3500)
        emit('buyer_email_alert', {
            'phone': session.get('user_phone', '9876543210'),
            'city': session.get('city', 'Unknown').upper() if session.get('city') else 'Unknown',
            'price': price
        }, broadcast=True)
    else:
        text = "No problem. We will notify you when the prices change." if session['language'] == 'en' else "ತೊಂದರೆಯಿಲ್ಲ. ಬೆಲೆಗಳು ಬದಲಾದಾಗ ನಾವು ನಿಮಗೆ ತಿಳಿಸುತ್ತೇವೆ."
        
    path = generate_ai_voice(text, session['language'])
    audio.play_voice(path)

@socketio.on('pest_action')
def handle_pest_action(data):
    problem = data['problem']
    print(f"\n[ACTION] Pest Problem Reported: {problem.upper()}")
    emit('status_update', {'msg': f'Pest Problem: {problem.replace("_", " ").upper()}'}, broadcast=True)
    
    solution_text = agri.get_pest_solution(problem, session['language'])
    
    path = generate_ai_voice(solution_text, session['language'])
    audio.play_voice(path)
    print(f"AI Solution: {solution_text}")

@socketio.on('sarkari_action')
def handle_sarkari_action(data):
    acreage = data['acreage']
    print(f"\n[ACTION] Acreage Selected: {acreage.upper()}")
    emit('status_update', {'msg': f'Acreage: {acreage.replace("_", " ").upper()}'}, broadcast=True)
    
    scheme_text = agri.get_scheme_details(acreage, session['language'])
    
    # --- NEW CODE FOR PANCHAYAT ANALYTICS ---
    scheme_name = "Kisan Samman Nidhi" if acreage == 'small' else "PM-KUSUM (Solar Pump)"
    emit('update_scheme_analytics', {'scheme': scheme_name}, broadcast=True)
    # ----------------------------------------
    
    path = generate_ai_voice(scheme_text, session['language'])
    audio.play_voice(path)
    print(f"AI Scheme Info: {scheme_text}")

@socketio.on('sarkari_final')
def handle_sarkari_final(data):
    decision = data['decision']
    print(f"\n[ACTION] Scheme Submission Decision: {decision.upper()}")
    emit('status_update', {'msg': f'Submission: {decision.upper()}'}, broadcast=True)
    
    if decision == 'agree':
        text = "Your application has been submitted successfully. Thank you!" if session['language'] == 'en' else "ನಿಮ್ಮ ಅರ್ಜಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ. ಧನ್ಯವಾದಗಳು!"
    else:
        text = "Application cancelled. Let us know if you need help with anything else." if session['language'] == 'en' else "ಅರ್ಜಿಯನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ. ನಿಮಗೆ ಬೇರೆ ಯಾವುದಾದರೂ ಸಹಾಯ ಬೇಕಾದಲ್ಲಿ ನಮಗೆ ತಿಳಿಸಿ."
        
    path = generate_ai_voice(text, session['language'])
    audio.play_voice(path)

@socketio.on('emergency_trigger')
def handle_emergency(data):
    level = data['level'] # RED, YELLOW, GREEN
    print(f"\n[EMERGENCY] {level} LEVEL ACTIVATED")
    emit('status_update', {'msg': f'🚨 EMERGENCY ACTIVATED: {level}'}, broadcast=True)
    
    # Immediately stop any other audio
    audio.stop_buffer()
    
    if level == 'RED':
        # 1. Start Priority logic
        instructions = health.get_triage_instructions("RED", session['language'])
        # 2. Trigger Hospital Email in Background
        threading.Thread(target=health.trigger_hospital_alert, args=(session['user_phone'],)).start()
        # 3. Speak instructions
        path = generate_ai_voice(instructions, session['language'])
        audio.play_voice(path)
        print(f"EMERGENCY INSTRUCTIONS: {instructions}")
    
    elif level == 'YELLOW':
        instructions = health.get_triage_instructions("YELLOW", session['language'])
        path = generate_ai_voice(instructions, session['language'])
        audio.play_voice(path)
        print(f"URGENT CARE: {instructions}")
        
    elif level == 'GREEN':
        instructions = health.get_triage_instructions("GREEN", session['language'])
        path = generate_ai_voice(instructions, session['language'])
        audio.play_voice(path)
        print(f"INFO: {instructions}")

# --- HELPER FUNCTIONS ---

def generate_ai_voice(text, lang):
    """
    Utility to bridge Brain text output to Audio playback.
    In the final build, this calls your TTS engine (gTTS/Coqui).
    """
    file_path = "static/audio/generated_reply.mp3"
    # Ensure directory exists
    os.makedirs("static/audio", exist_ok=True)
    tts = gTTS(text, lang=lang)
    tts.save(file_path)
    return file_path

if __name__ == '__main__':
    print("Garuda Sanket God-Mode Server Active...")
    socketio.run(app, debug=True, host='0.0.0.0', port=5000)